# Generated by Django 5.2.3 on 2025-06-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course_offering',
        ),
    ]
