# Generated by Django 5.2.3 on 2025-06-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_remove_assignment_course_offering_and_more'),
        ('courses', '0003_alter_courseoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
            preserve_default=False,
        ),
    ]
