# Generated by Django 5.2.3 on 2025-06-27 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='sections',
            field=models.ManyToManyField(blank=True, to='courses.section'),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('schedule', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='termcourse',
            unique_together={('schedule', 'classroom')},
        ),
    ]
