# Generated by Django 5.2.3 on 2025-06-26 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField()),
                ('enrolled_students', models.PositiveSmallIntegerField(default=0)),
                ('schedule', models.CharField(help_text='e.g., Mon/Wed 10:00-11:30', max_length=100)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'user_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('credits', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('enrolled_students', models.PositiveSmallIntegerField(default=0)),
                ('schedule', models.CharField(help_text='e.g., Mon/Wed 10:00-11:30', max_length=100)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(blank=True, to='courses.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/materials/')),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse')),
            ],
        ),
    ]
