# Generated by Django 5.2.3 on 2025-06-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termcourse',
            old_name='instructor',
            new_name='professor',
        ),
    ]
