# Generated by Django 5.2.3 on 2025-06-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assignment_course_exam_course'),
        ('courses', '0003_alter_courseoffering_unique_together_and_more'),
        ('notifications', '0003_remove_resource_course_offering_resource_course'),
        ('student_services', '0003_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOffering',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('schedule', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='termcourse',
            unique_together={('schedule', 'classroom')},
        ),
    ]
