# Generated by Django 5.2.3 on 2025-06-26 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseoffering_unique_together_and_more'),
        ('student_services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default=-301, on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_offering',
        ),
    ]
