# Generated by Django 5.2.3 on 2025-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('degree', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('PhD', 'Doctor of Philosophy')], max_length=10)),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in years')),
                ('description', models.TextField()),
                ('total_credits', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', 'semester'],
            },
        ),
    ]
