# Generated by Django 5.2.3 on 2025-06-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseoffering_unique_together_and_more'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course_offering',
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.termcourse'),
        ),
    ]
